-- Session #1
START TRANSACTION;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM pizzeria;
SELECT * FROM pizzeria;
COMMIT;
SELECT * FROM pizzeria;

-- Session #2
START TRANSACTION;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
UPDATE pizzeria SET rating = 3 WHERE name = 'Pizza Hut';
COMMIT;
SELECT * FROM pizzeria;

